travis:
  secure:
    BINSTAR_TOKEN: fDYLS7huMKeBWaWPUxrMTyMMwvyQisgjex3WjZFH1wLvWe1nWnK2dpLJPR/nErQB1L2Ea6Mo9Mj9SC6r0qe20PCvjM6l4uKnu2E4lRd1n5SsD7ycD2y9mMmC7EFpUhnfZrTJ5V/C2okKcUUNvu/aVnd0AMxY28HxLoJL+4luOGuvyIp5dhCR8yCuuEJz3d/974TcRZ+SqB+zm4rjU6PK1nEmFFBxYspYfKzbcq91UZLEG93mhd4+E+JoIS6F8Cz/7VkdrIv4QL/aBFkq2V7VmFAHUI8oVfsBJAIThUPpOqyLJXsfdRwH6+wAmKM18xVjEa6SZyBN/JiKg89DcUCVGoKm21kBh6Dcqxd+6Go0UdFoQ6WQcXyy/ry5bg27jZC0Y90+RC/E4FkYjWyLx3BAfRK9vfYMsRLVP8mpzJQvX+y8nGrgNyBQU71nueHjqHTy4Np/t/QZzrVxLrbH2gdTFRy98QXYThT+CTbBNOgeWRq4hOXPcs/IXxBeLHtn03pQ6fpOj/N3rZBU9QAiV3T3IC++zHgUG2GaDx0ILV9npkI2BqaE1505ua/qViEq1SF+KvINBNBcJ+Su0JicXRAW6A9kYjp+oKysTTXGyyu8/6Uebz9MR0mBYpFa3vnwbz0eP7dMM13M551MqPasLj+rG8K1pk239h8TxcHCXO5q4D8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
